inherit_from:
  - ".rubocop-rails.yml"
  - ".rubocop-rspec.yml"

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0.0
  TargetRailsVersion: 6.0
  Exclude:
    - "**/db/migrate/*"
    - "**/Gemfile.lock"
    - "**/Rakefile"
    - "**/rails"
    - "**/vendor/**/*"
    - "**/spec_helper.rb"
    - "node_modules/**/*"
    - "bin/*"
